apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-8
  template:
    metadata:
      labels:
        app: project-8
    spec:
      containers:
      - name: project-8
        image: mukeshr29/project-8
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
